sudo: required
dist: xenial

jobs:
  include:
    - os: linux
      arch: amd64
      env:
        - CREATE_CHANGELOG=1
    - os: linux
      arch: arm64

services:
  - docker

language: go

go:
  - 1.14.x

addons:
  apt:
    update: true

before_script:
  - make check-license || travis_terminate 1;
  # 1. Install kubectl binary
  # 2. Install minikube
  # 3. Initialize minukube and kubernetes config directory
  # 4. Start minukube server
  - if [ "$TRAVIS_CPU_ARCH" == "amd64" ]; then
      make lint-docker || travis_terminate 1;
      curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/v1.13.0/bin/linux/amd64/kubectl && chmod +x kubectl && sudo mv kubectl /usr/local/bin/ || travis_terminate 1;
      curl -Lo minikube https://storage.googleapis.com/minikube/releases/v0.35.0/minikube-linux-amd64 && chmod +x minikube && sudo mv minikube /usr/local/bin/ || travis_terminate 1;
      mkdir -p $HOME/.kube $HOME/.minikube;
      sudo minikube start --vm-driver=none --kubernetes-version=v1.13.0 || travis_terminate 1;
      sudo chown -R $USER $HOME/.kube $HOME/.minikube;
      JSONPATH='{range .items[*]}{@.metadata.name}:{range @.status.conditions[*]}{@.type}={@.status};{end}{end}'; until kubectl get nodes -o jsonpath="$JSONPATH" 2>&1 | grep -q "Ready=True"; do sleep 1; done;
    fi

script:
  - make build && make container || travis_terminate 1;
  # In travis we use openebs operator from openebs/openebs:master only.
  - if [ "$TRAVIS_CPU_ARCH" == "amd64" ]; then
      kubectl cluster-info;
      export VELERO_RELEASE=v1.0.0;
      export OPENEBS_RELEASE=master;
      ./script/install-openebs.sh && ./script/install-velero.sh && travis_wait 30 make test || travis_terminate 1;
    fi

after_success:
  - make deploy-image
  # create changelog for release/rc tag
  - if [ ! -z $TRAVIS_TAG ] && [ $CREATE_CHANGELOG -eq 1 ] && [ "$TRAVIS_REPO_SLUG" == "openebs/velero-plugin" ]; then
      ./script/create_changelog "$TRAVIS_REPO_SLUG" "$TRAVIS_TAG" "master";
    fi

notifications:
  email:
    recipients:
    - kiran.mova@mayadata.io
    - mayank.patel@mayadata.io

branches:
  except:
    - /^*-v[0-9]/
